### ISSUE TITLE
Online documentation

### ISSUE THREAD

**Issue by LegacyDebaditya** [cool-RR/grid_royale#48]
Hey I made a interactive online documentation for your Grid_Royale project.
It is hosted at [Website](https://grid-royale-docs.netlify.app/)

**Comment by cool-RR** [comment]
What are the advantages here?

**Comment by LegacyDebaditya** [comment]
The advantages are that anyone using the project will be easily understand what the project is as humans like GUI more than normal boring text .

**Comment by cool-RR** [comment]
Can you point out where specifically there is a gui element in your docs
that gives a better experience than the equivalent markdown on GitHub?

**Comment by LegacyDebaditya** [comment]
My website has colors and your pieces of code are colored with syntax which is more interactive.

**Comment by cool-RR** [comment]
Can you give me a screenshot of these specific pieces of code you're talking about?

**Comment by LegacyDebaditya** [comment]
![proof-code](https://user-images.githubusercontent.com/63513685/100848695-7ca06000-34a7-11eb-9603-47a0cc6d3432.PNG)
Here's the screenshot
![proof-code-2](https://user-images.githubusercontent.com/63513685/100848937-d9037f80-34a7-11eb-938c-01a2a9bc1334.PNG)

**Comment by cool-RR** [comment]
Sorry, not convinced there's an improvement here.

**Comment by LegacyDebaditya** [comment]
Ok do you want the website or will I delete ,although it is made of React and is quite fast

**Comment by cool-RR** [comment]
As far as I'm concerned it can be deleted.
